// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
)

type ContactInfo struct {
	ent.Schema
}

func (ContactInfo) Fields() []ent.Field {
	return []ent.Field{field.Int("id"), field.String("name").Optional(), field.String("email").Optional(), field.String("messages").Optional(), field.Time("created_at").Optional()}
}
func (ContactInfo) Edges() []ent.Edge {
	return nil
}
func (ContactInfo) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "ContactInfo"}}
}
