// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ContactInfo is the predicate function for contactinfo builders.
type ContactInfo func(*sql.Selector)

// SchemaMigration is the predicate function for schemamigration builders.
type SchemaMigration func(*sql.Selector)
