// Code generated by ent, DO NOT EDIT.

package contactinfo

import (
	"assignment4/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldEQ(FieldName, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldEQ(FieldEmail, v))
}

// Messages applies equality check predicate on the "messages" field. It's identical to MessagesEQ.
func Messages(v string) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldEQ(FieldMessages, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldEQ(FieldCreatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldHasSuffix(FieldName, v))
}

// NameIsNil applies the IsNil predicate on the "name" field.
func NameIsNil() predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldIsNull(FieldName))
}

// NameNotNil applies the NotNil predicate on the "name" field.
func NameNotNil() predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldNotNull(FieldName))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldContainsFold(FieldName, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailIsNil applies the IsNil predicate on the "email" field.
func EmailIsNil() predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldIsNull(FieldEmail))
}

// EmailNotNil applies the NotNil predicate on the "email" field.
func EmailNotNil() predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldNotNull(FieldEmail))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldContainsFold(FieldEmail, v))
}

// MessagesEQ applies the EQ predicate on the "messages" field.
func MessagesEQ(v string) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldEQ(FieldMessages, v))
}

// MessagesNEQ applies the NEQ predicate on the "messages" field.
func MessagesNEQ(v string) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldNEQ(FieldMessages, v))
}

// MessagesIn applies the In predicate on the "messages" field.
func MessagesIn(vs ...string) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldIn(FieldMessages, vs...))
}

// MessagesNotIn applies the NotIn predicate on the "messages" field.
func MessagesNotIn(vs ...string) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldNotIn(FieldMessages, vs...))
}

// MessagesGT applies the GT predicate on the "messages" field.
func MessagesGT(v string) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldGT(FieldMessages, v))
}

// MessagesGTE applies the GTE predicate on the "messages" field.
func MessagesGTE(v string) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldGTE(FieldMessages, v))
}

// MessagesLT applies the LT predicate on the "messages" field.
func MessagesLT(v string) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldLT(FieldMessages, v))
}

// MessagesLTE applies the LTE predicate on the "messages" field.
func MessagesLTE(v string) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldLTE(FieldMessages, v))
}

// MessagesContains applies the Contains predicate on the "messages" field.
func MessagesContains(v string) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldContains(FieldMessages, v))
}

// MessagesHasPrefix applies the HasPrefix predicate on the "messages" field.
func MessagesHasPrefix(v string) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldHasPrefix(FieldMessages, v))
}

// MessagesHasSuffix applies the HasSuffix predicate on the "messages" field.
func MessagesHasSuffix(v string) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldHasSuffix(FieldMessages, v))
}

// MessagesIsNil applies the IsNil predicate on the "messages" field.
func MessagesIsNil() predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldIsNull(FieldMessages))
}

// MessagesNotNil applies the NotNil predicate on the "messages" field.
func MessagesNotNil() predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldNotNull(FieldMessages))
}

// MessagesEqualFold applies the EqualFold predicate on the "messages" field.
func MessagesEqualFold(v string) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldEqualFold(FieldMessages, v))
}

// MessagesContainsFold applies the ContainsFold predicate on the "messages" field.
func MessagesContainsFold(v string) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldContainsFold(FieldMessages, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.ContactInfo {
	return predicate.ContactInfo(sql.FieldNotNull(FieldCreatedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ContactInfo) predicate.ContactInfo {
	return predicate.ContactInfo(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ContactInfo) predicate.ContactInfo {
	return predicate.ContactInfo(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ContactInfo) predicate.ContactInfo {
	return predicate.ContactInfo(sql.NotPredicates(p))
}
