// Code generated by ent, DO NOT EDIT.

package ent

import (
	"assignment4/ent/contactinfo"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ContactInfo is the model entity for the ContactInfo schema.
type ContactInfo struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// Messages holds the value of the "messages" field.
	Messages string `json:"messages,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ContactInfo) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case contactinfo.FieldID:
			values[i] = new(sql.NullInt64)
		case contactinfo.FieldName, contactinfo.FieldEmail, contactinfo.FieldMessages:
			values[i] = new(sql.NullString)
		case contactinfo.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ContactInfo fields.
func (ci *ContactInfo) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case contactinfo.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ci.ID = int(value.Int64)
		case contactinfo.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				ci.Name = value.String
			}
		case contactinfo.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				ci.Email = value.String
			}
		case contactinfo.FieldMessages:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field messages", values[i])
			} else if value.Valid {
				ci.Messages = value.String
			}
		case contactinfo.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ci.CreatedAt = value.Time
			}
		default:
			ci.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ContactInfo.
// This includes values selected through modifiers, order, etc.
func (ci *ContactInfo) Value(name string) (ent.Value, error) {
	return ci.selectValues.Get(name)
}

// Update returns a builder for updating this ContactInfo.
// Note that you need to call ContactInfo.Unwrap() before calling this method if this ContactInfo
// was returned from a transaction, and the transaction was committed or rolled back.
func (ci *ContactInfo) Update() *ContactInfoUpdateOne {
	return NewContactInfoClient(ci.config).UpdateOne(ci)
}

// Unwrap unwraps the ContactInfo entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ci *ContactInfo) Unwrap() *ContactInfo {
	_tx, ok := ci.config.driver.(*txDriver)
	if !ok {
		panic("ent: ContactInfo is not a transactional entity")
	}
	ci.config.driver = _tx.drv
	return ci
}

// String implements the fmt.Stringer.
func (ci *ContactInfo) String() string {
	var builder strings.Builder
	builder.WriteString("ContactInfo(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ci.ID))
	builder.WriteString("name=")
	builder.WriteString(ci.Name)
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(ci.Email)
	builder.WriteString(", ")
	builder.WriteString("messages=")
	builder.WriteString(ci.Messages)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(ci.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ContactInfos is a parsable slice of ContactInfo.
type ContactInfos []*ContactInfo
