// Code generated by ent, DO NOT EDIT.

package ent

import (
	"assignment4/ent/contactinfo"
	"assignment4/ent/predicate"
	"assignment4/ent/schemamigration"
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeContactInfo     = "ContactInfo"
	TypeSchemaMigration = "SchemaMigration"
)

// ContactInfoMutation represents an operation that mutates the ContactInfo nodes in the graph.
type ContactInfoMutation struct {
	config
	op            Op
	typ           string
	id            *int
	name          *string
	email         *string
	messages      *string
	created_at    *time.Time
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*ContactInfo, error)
	predicates    []predicate.ContactInfo
}

var _ ent.Mutation = (*ContactInfoMutation)(nil)

// contactinfoOption allows management of the mutation configuration using functional options.
type contactinfoOption func(*ContactInfoMutation)

// newContactInfoMutation creates new mutation for the ContactInfo entity.
func newContactInfoMutation(c config, op Op, opts ...contactinfoOption) *ContactInfoMutation {
	m := &ContactInfoMutation{
		config:        c,
		op:            op,
		typ:           TypeContactInfo,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withContactInfoID sets the ID field of the mutation.
func withContactInfoID(id int) contactinfoOption {
	return func(m *ContactInfoMutation) {
		var (
			err   error
			once  sync.Once
			value *ContactInfo
		)
		m.oldValue = func(ctx context.Context) (*ContactInfo, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().ContactInfo.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withContactInfo sets the old ContactInfo of the mutation.
func withContactInfo(node *ContactInfo) contactinfoOption {
	return func(m *ContactInfoMutation) {
		m.oldValue = func(context.Context) (*ContactInfo, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ContactInfoMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ContactInfoMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of ContactInfo entities.
func (m *ContactInfoMutation) SetID(id int) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *ContactInfoMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *ContactInfoMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().ContactInfo.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *ContactInfoMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *ContactInfoMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the ContactInfo entity.
// If the ContactInfo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ContactInfoMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ClearName clears the value of the "name" field.
func (m *ContactInfoMutation) ClearName() {
	m.name = nil
	m.clearedFields[contactinfo.FieldName] = struct{}{}
}

// NameCleared returns if the "name" field was cleared in this mutation.
func (m *ContactInfoMutation) NameCleared() bool {
	_, ok := m.clearedFields[contactinfo.FieldName]
	return ok
}

// ResetName resets all changes to the "name" field.
func (m *ContactInfoMutation) ResetName() {
	m.name = nil
	delete(m.clearedFields, contactinfo.FieldName)
}

// SetEmail sets the "email" field.
func (m *ContactInfoMutation) SetEmail(s string) {
	m.email = &s
}

// Email returns the value of the "email" field in the mutation.
func (m *ContactInfoMutation) Email() (r string, exists bool) {
	v := m.email
	if v == nil {
		return
	}
	return *v, true
}

// OldEmail returns the old "email" field's value of the ContactInfo entity.
// If the ContactInfo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ContactInfoMutation) OldEmail(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEmail is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEmail requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEmail: %w", err)
	}
	return oldValue.Email, nil
}

// ClearEmail clears the value of the "email" field.
func (m *ContactInfoMutation) ClearEmail() {
	m.email = nil
	m.clearedFields[contactinfo.FieldEmail] = struct{}{}
}

// EmailCleared returns if the "email" field was cleared in this mutation.
func (m *ContactInfoMutation) EmailCleared() bool {
	_, ok := m.clearedFields[contactinfo.FieldEmail]
	return ok
}

// ResetEmail resets all changes to the "email" field.
func (m *ContactInfoMutation) ResetEmail() {
	m.email = nil
	delete(m.clearedFields, contactinfo.FieldEmail)
}

// SetMessages sets the "messages" field.
func (m *ContactInfoMutation) SetMessages(s string) {
	m.messages = &s
}

// Messages returns the value of the "messages" field in the mutation.
func (m *ContactInfoMutation) Messages() (r string, exists bool) {
	v := m.messages
	if v == nil {
		return
	}
	return *v, true
}

// OldMessages returns the old "messages" field's value of the ContactInfo entity.
// If the ContactInfo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ContactInfoMutation) OldMessages(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldMessages is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldMessages requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMessages: %w", err)
	}
	return oldValue.Messages, nil
}

// ClearMessages clears the value of the "messages" field.
func (m *ContactInfoMutation) ClearMessages() {
	m.messages = nil
	m.clearedFields[contactinfo.FieldMessages] = struct{}{}
}

// MessagesCleared returns if the "messages" field was cleared in this mutation.
func (m *ContactInfoMutation) MessagesCleared() bool {
	_, ok := m.clearedFields[contactinfo.FieldMessages]
	return ok
}

// ResetMessages resets all changes to the "messages" field.
func (m *ContactInfoMutation) ResetMessages() {
	m.messages = nil
	delete(m.clearedFields, contactinfo.FieldMessages)
}

// SetCreatedAt sets the "created_at" field.
func (m *ContactInfoMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *ContactInfoMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the ContactInfo entity.
// If the ContactInfo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ContactInfoMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ClearCreatedAt clears the value of the "created_at" field.
func (m *ContactInfoMutation) ClearCreatedAt() {
	m.created_at = nil
	m.clearedFields[contactinfo.FieldCreatedAt] = struct{}{}
}

// CreatedAtCleared returns if the "created_at" field was cleared in this mutation.
func (m *ContactInfoMutation) CreatedAtCleared() bool {
	_, ok := m.clearedFields[contactinfo.FieldCreatedAt]
	return ok
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *ContactInfoMutation) ResetCreatedAt() {
	m.created_at = nil
	delete(m.clearedFields, contactinfo.FieldCreatedAt)
}

// Where appends a list predicates to the ContactInfoMutation builder.
func (m *ContactInfoMutation) Where(ps ...predicate.ContactInfo) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the ContactInfoMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *ContactInfoMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.ContactInfo, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *ContactInfoMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *ContactInfoMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (ContactInfo).
func (m *ContactInfoMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ContactInfoMutation) Fields() []string {
	fields := make([]string, 0, 4)
	if m.name != nil {
		fields = append(fields, contactinfo.FieldName)
	}
	if m.email != nil {
		fields = append(fields, contactinfo.FieldEmail)
	}
	if m.messages != nil {
		fields = append(fields, contactinfo.FieldMessages)
	}
	if m.created_at != nil {
		fields = append(fields, contactinfo.FieldCreatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ContactInfoMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case contactinfo.FieldName:
		return m.Name()
	case contactinfo.FieldEmail:
		return m.Email()
	case contactinfo.FieldMessages:
		return m.Messages()
	case contactinfo.FieldCreatedAt:
		return m.CreatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ContactInfoMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case contactinfo.FieldName:
		return m.OldName(ctx)
	case contactinfo.FieldEmail:
		return m.OldEmail(ctx)
	case contactinfo.FieldMessages:
		return m.OldMessages(ctx)
	case contactinfo.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown ContactInfo field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ContactInfoMutation) SetField(name string, value ent.Value) error {
	switch name {
	case contactinfo.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case contactinfo.FieldEmail:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEmail(v)
		return nil
	case contactinfo.FieldMessages:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMessages(v)
		return nil
	case contactinfo.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown ContactInfo field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ContactInfoMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ContactInfoMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ContactInfoMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown ContactInfo numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ContactInfoMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(contactinfo.FieldName) {
		fields = append(fields, contactinfo.FieldName)
	}
	if m.FieldCleared(contactinfo.FieldEmail) {
		fields = append(fields, contactinfo.FieldEmail)
	}
	if m.FieldCleared(contactinfo.FieldMessages) {
		fields = append(fields, contactinfo.FieldMessages)
	}
	if m.FieldCleared(contactinfo.FieldCreatedAt) {
		fields = append(fields, contactinfo.FieldCreatedAt)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ContactInfoMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ContactInfoMutation) ClearField(name string) error {
	switch name {
	case contactinfo.FieldName:
		m.ClearName()
		return nil
	case contactinfo.FieldEmail:
		m.ClearEmail()
		return nil
	case contactinfo.FieldMessages:
		m.ClearMessages()
		return nil
	case contactinfo.FieldCreatedAt:
		m.ClearCreatedAt()
		return nil
	}
	return fmt.Errorf("unknown ContactInfo nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ContactInfoMutation) ResetField(name string) error {
	switch name {
	case contactinfo.FieldName:
		m.ResetName()
		return nil
	case contactinfo.FieldEmail:
		m.ResetEmail()
		return nil
	case contactinfo.FieldMessages:
		m.ResetMessages()
		return nil
	case contactinfo.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	}
	return fmt.Errorf("unknown ContactInfo field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ContactInfoMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ContactInfoMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ContactInfoMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ContactInfoMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ContactInfoMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ContactInfoMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ContactInfoMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown ContactInfo unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ContactInfoMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown ContactInfo edge %s", name)
}

// SchemaMigrationMutation represents an operation that mutates the SchemaMigration nodes in the graph.
type SchemaMigrationMutation struct {
	config
	op            Op
	typ           string
	id            *int
	dirty         *bool
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*SchemaMigration, error)
	predicates    []predicate.SchemaMigration
}

var _ ent.Mutation = (*SchemaMigrationMutation)(nil)

// schemamigrationOption allows management of the mutation configuration using functional options.
type schemamigrationOption func(*SchemaMigrationMutation)

// newSchemaMigrationMutation creates new mutation for the SchemaMigration entity.
func newSchemaMigrationMutation(c config, op Op, opts ...schemamigrationOption) *SchemaMigrationMutation {
	m := &SchemaMigrationMutation{
		config:        c,
		op:            op,
		typ:           TypeSchemaMigration,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withSchemaMigrationID sets the ID field of the mutation.
func withSchemaMigrationID(id int) schemamigrationOption {
	return func(m *SchemaMigrationMutation) {
		var (
			err   error
			once  sync.Once
			value *SchemaMigration
		)
		m.oldValue = func(ctx context.Context) (*SchemaMigration, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().SchemaMigration.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withSchemaMigration sets the old SchemaMigration of the mutation.
func withSchemaMigration(node *SchemaMigration) schemamigrationOption {
	return func(m *SchemaMigrationMutation) {
		m.oldValue = func(context.Context) (*SchemaMigration, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m SchemaMigrationMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m SchemaMigrationMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of SchemaMigration entities.
func (m *SchemaMigrationMutation) SetID(id int) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *SchemaMigrationMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *SchemaMigrationMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().SchemaMigration.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetDirty sets the "dirty" field.
func (m *SchemaMigrationMutation) SetDirty(b bool) {
	m.dirty = &b
}

// Dirty returns the value of the "dirty" field in the mutation.
func (m *SchemaMigrationMutation) Dirty() (r bool, exists bool) {
	v := m.dirty
	if v == nil {
		return
	}
	return *v, true
}

// OldDirty returns the old "dirty" field's value of the SchemaMigration entity.
// If the SchemaMigration object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SchemaMigrationMutation) OldDirty(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDirty is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDirty requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDirty: %w", err)
	}
	return oldValue.Dirty, nil
}

// ResetDirty resets all changes to the "dirty" field.
func (m *SchemaMigrationMutation) ResetDirty() {
	m.dirty = nil
}

// Where appends a list predicates to the SchemaMigrationMutation builder.
func (m *SchemaMigrationMutation) Where(ps ...predicate.SchemaMigration) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the SchemaMigrationMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *SchemaMigrationMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.SchemaMigration, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *SchemaMigrationMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *SchemaMigrationMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (SchemaMigration).
func (m *SchemaMigrationMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *SchemaMigrationMutation) Fields() []string {
	fields := make([]string, 0, 1)
	if m.dirty != nil {
		fields = append(fields, schemamigration.FieldDirty)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *SchemaMigrationMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case schemamigration.FieldDirty:
		return m.Dirty()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *SchemaMigrationMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case schemamigration.FieldDirty:
		return m.OldDirty(ctx)
	}
	return nil, fmt.Errorf("unknown SchemaMigration field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *SchemaMigrationMutation) SetField(name string, value ent.Value) error {
	switch name {
	case schemamigration.FieldDirty:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDirty(v)
		return nil
	}
	return fmt.Errorf("unknown SchemaMigration field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *SchemaMigrationMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *SchemaMigrationMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *SchemaMigrationMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown SchemaMigration numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *SchemaMigrationMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *SchemaMigrationMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *SchemaMigrationMutation) ClearField(name string) error {
	return fmt.Errorf("unknown SchemaMigration nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *SchemaMigrationMutation) ResetField(name string) error {
	switch name {
	case schemamigration.FieldDirty:
		m.ResetDirty()
		return nil
	}
	return fmt.Errorf("unknown SchemaMigration field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *SchemaMigrationMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *SchemaMigrationMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *SchemaMigrationMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *SchemaMigrationMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *SchemaMigrationMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *SchemaMigrationMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *SchemaMigrationMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown SchemaMigration unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *SchemaMigrationMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown SchemaMigration edge %s", name)
}
